/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import * as THREE from "three";
const HeartModel = forwardRef((props, ref) => {
  // const model = useLoader(GLTFLoader, '/Human heart.glb')
// lazy async loading
  const { nodes, materials } = useGLTF("/Human heart.glb");
  const meshBasicMaterial = new THREE.MeshBasicMaterial({
    color: "white",
    wireframe: true,
  });

  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          ref={ref}
          geometry={nodes.human_heart1.geometry}
          material={meshBasicMaterial}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/Human heart.glb");

export default HeartModel;
